version: "3.9"

services:
  api:
    build: ./TaskManager
    container_name: taskmanager_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Database=taskdb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./taskmanagerui
    container_name: taskmanager_front
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: taskmanager_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
